version: "3"

services:

  movie-api:
    image: node:12.6.0 
    container_name: movie-api-docker
    volumes:
      - ./:/home/app
    environment:
      PORT: 3000
      DB_HOST: 'host.docker.internal' #Don't change this value. This tells docker to use the host ip (your local ip) to connect to the database. 
      DB_USER: 'root' 
      DB_PASS: 'root'
      DB_NAME: 'movie_db' #Don't change this. All queries to the database depend on this name.
    working_dir: /home/app
    command: bash -c "npm start"
    ports:
      - 8080:3000
    depends_on:
      - "db"
    
  db:
    image: mysql:5.7.26
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data_model:/docker-entrypoint-initdb.d